name: create_production_pull_request

on:
  push:
    branches:
      - develop

jobs:
  auto-pull-request:
    name: create_production_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: "Production Release"
          PULL_REQUEST_BODY: |
            # PRODUCTION RELEASE
            ## Changelog
